#!/bin/bash

THIS=${PWD##}

rm -rf \
	"$HOME/.bashrc" \
	"$HOME/.bash_profile" \
	"$HOME/.bash_func" \
	"$HOME/.profile" \
	"$HOME/.vimrc" \
	"$HOME/.vim"

ln -sF "$THIS/.bashrc" "$HOME/.bashrc"
ln -sF "$THIS/.profile" "$HOME/.profile"
ln -sF "$THIS/.profile" "$HOME/.bash_profile"
ln -sF "$THIS/.bash_func" "$HOME/.bash_func"

# /bin 
mkdir -p "$HOME/bin"

# git-completion.bash
rm "$HOME/.git-completion.bash"
curl -LSo \
	"$HOME/.git-completion.bash" \
	https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash

# vim
ln -sF "$THIS/.vimrc" "$HOME/.vimrc"
ln -sF "$THIS/.vim" "$HOME/.vim"

# install pathogen
rm -rf "$THIS/.vim/autoload" "$THIS/.vim/bundle"
mkdir -p "$THIS/.vim/autoload" "$THIS/.vim/bundle"

curl -LSo "$THIS/.vim/autoload/pathogen.vim" \
	https://tpo.pe/pathogen.vim

# install pathogen bundles
cd "$THIS/.vim/bundle"
git clone https://github.com/unc0/vim-gorilla-script.git
git clone https://github.com/sterpe/vim-algol68.git
git clone https://github.com/elzr/vim-json.git
git clone https://github.com/sterpe/vim-jslint.git

# npm install this one's dependencies
cd vim-jslint/ftplugin/javascript/vim-jslint
npm install
cd "$THIS/.vim/bundle"

#install latest molokai color scheme
rm -rf "$THIS/.vim/colors"
mkdir -p "$THIS/.vim/colors"

curl -LSo \
	"$THIS/.vim/colors/molokai.vim" \
	https://raw.githubusercontent.com/tomasr/molokai/master/colors/molokai.vim

# /.swp 
mkdir -p "$HOME/.swp"

rm -rf "$THIS/tars"
mkdir -p "$THIS/tars"

curl -LSo \
	"$THIS/tars/algol68g-2.8.tar.gz" \
	http://jmvdveer.home.xs4all.nl/algol68g-2.8.tar.gz

curl -LSo \
	"$THIS/tars/ed-1.10.tar.lz" \
	http://gnu.mirrors.hoobly.com/gnu/ed/ed-1.10.tar.lz

# curl -LSo \
# 	"$THIS/tars/mplus-TESTFLIGHT-058.tar.xz" \
# 	http://sourceforge.jp/frs/redir.php?m=jaist&f=%2Fmplus-fonts%2F6650%2Fmplus-TESTFLIGHT-058.tar.xz

